# Generated by Django 2.0.6 on 2019-04-03 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_name', models.CharField(default='', max_length=225)),
                ('user_email', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='', max_length=20)),
                ('user_mobile', models.CharField(default='', max_length=255)),
                ('user_gender', models.CharField(default='', max_length=10)),
                ('user_dob', models.CharField(default='', max_length=255)),
                ('user_isactive', models.BooleanField(default=True)),
                ('user_isavailable', models.BooleanField(default=True)),
                ('login_time', models.CharField(default='', max_length=255)),
                ('login_date', models.CharField(default='', max_length=255)),
                ('logout_time', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=225, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userapp.UserRole'),
        ),
    ]
