# Generated by Django 2.0.6 on 2019-04-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20190416_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='otptime',
        ),
    ]
