# Generated by Django 2.0.6 on 2019-04-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20190417_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='otp_time',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
