# Generated by Django 2.0.6 on 2019-04-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20190417_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupuser',
            old_name='SignUp_date',
            new_name='SignUp_datetime',
        ),
        migrations.RemoveField(
            model_name='signupuser',
            name='SignUp_time',
        ),
    ]
