# Generated by Django 2.0.6 on 2019-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20190418_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='auth_token',
            field=models.CharField(default='', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='dob',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='mobile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
