# Generated by Django 2.0.6 on 2019-04-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20190422_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupuser',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='signupuser',
            name='is_verified',
        ),
    ]
