# Generated by Django 2.0.6 on 2019-04-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20190422_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='auth_token',
            field=models.CharField(default='', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='is_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
